# Generated by Django 4.2.1 on 2023-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField()),
                ("number", models.CharField()),
                ("zip_code", models.IntegerField()),
                ("city", models.CharField()),
                ("state", models.CharField(max_length=2)),
            ],
        ),
    ]
