# Generated by Django 4.2.1 on 2023-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_orderproducts_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Placed", "Placed"),
                    ("In Progress", "Pending"),
                    ("Delivered", "Delivered"),
                ],
                default="Order Placed",
            ),
        ),
    ]
